apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: swiftkube
servers: 1
agents: 2
image: docker.io/rancher/k3s:v1.32.0-k3s1
options:
  k3d:
    wait: true
    timeout: "120s"
    disableLoadbalancer: true
    disableImageVolume: true
  k3s:
    extraArgs:
      - arg: --disable=traefik,servicelb,metrics-server
        nodeFilters:
          - server:*
