name: "CI"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "*" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v5
    - name: Install SwiftFormat
      uses: Cyberbeni/install-swift-tool@v2
      with:
        url: https://github.com/nicklockwood/SwiftFormat
    - name: Lint Sources
      run: swiftformat --lint Sources

  linux:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      matrix:
        image: ["swift:5.10", "swift:6.0", "swift:6.1", "swiftlang/swift:nightly-6.2-noble"]
    container:
      image: ${{ matrix.image }}
    steps:
    - name: Checkout
      uses: actions/checkout@v5
    - name: Build
      run: swift build

  macos:
    runs-on: macOS-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v5
    - name: SPM Cache
      uses: actions/cache@v4
      with:
        path: .build
        key: macos-latests-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          macos-latests-
    - name: Build
      run: swift build

  ios:
    runs-on: macOS-latest
    strategy:
      matrix:
        destination: 
          - "platform=iOS Simulator,OS=18.5,name=iPad Pro 13-inch (M4)"
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Build
        run: set -o pipefail && xcodebuild -scheme SwiftkubeClient -destination "${{ matrix.destination }}" clean build | xcpretty
