name: "Minikube"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "*" ]

jobs:

  test:
    runs-on: ubuntu-22.04
    continue-on-error: false
    strategy:
      matrix:
        swift: ["5.10", "6.0", "6.1"]
    steps:
    - name: Checkout
      uses: actions/checkout@v5
    - name: SPM Cache
      uses: actions/cache@v4
      with:
        path: .build
        key: ${{ matrix.swift }}-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ matrix.swift }}-
    - name: Start minikube
      uses: medyagh/setup-minikube@latest
      id: minikube
      with:
        minikube-version: 1.35.0
    - uses: SwiftyLab/setup-swift@latest
      with:
        swift-version: ${{ matrix.swift }}
    - name: Get swift version
      run: swift --version
    - name: Build
      run: swift build
    - name: Test
      run: swift test
